### ISSUE TITLE
Same HU shown with picking processed and not processed 

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend-legacy#1942]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The same HU is shown with picking processed and not processed, for 2 different orderlines in picking terminal.
http://recordit.co/BMNyfQvBFa
#### Which are the steps to reproduce?
1. Sales order with 2 orderlines, same product
2. In picking terminal pick a HU of that product in a picking slot
3. process the picking, while 1 orderline is selected: HU becomes read-only
4. select the other orderline: HU is not read-only anymore, as if the picking was not processed
### What is the expected or desired behavior?
HU shall be shown the same for all orderlines.

**Comment by siemiatj** [comment]
After looking for a suitable test case for a year, when I've finally found one I'm getting error from the server when running quick action :/ Any ideas ? @teosarca @metas-ts 

http://recordit.co/Dqztnbj44n

**Comment by metas-dh** [comment]
afais the error says "More than 1 record found", can it be related to  #1941? since the HU is displayed in the picking slot, but also still shown in the HU Editor for selection? @teosarca wdyt?

**Comment by teosarca** [comment]
@siemiatj  @metas-dh  The issue is not related with this task but ofc is blocking this one.
The problem is described and shall be solved here: https://github.com/metasfresh/metasfresh/issues/4562

More, in this particular case (w101) there are 3 distribution networks with `empties` but we shall have only one:
![image](https://user-images.githubusercontent.com/1244701/45278236-db4b1f00-b4d4-11e8-8a0a-10dbca2fe6dc.png)


Atm, i've kept only the first one. If, while testing on w101, we got an error because empties could not be collected, we need to create the distribution line inside first distribution network:
![image](https://user-images.githubusercontent.com/1244701/45278268-09306380-b4d5-11e8-9223-f5830f5e6a8e.png)

**Comment by metas-dh** [comment]
this is not happening anymore, was probably fixed with the several tasks on picking terminal we had in the recent weeks.
